//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swim4Life
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class dbEntities : DbContext
    {
        public dbEntities()
            : base("name=dbEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Employees_Tbl> Employees_Tbl { get; set; }
        public virtual DbSet<Expense_Tbl> Expense_Tbl { get; set; }
        public virtual DbSet<Pool_Tbl> Pool_Tbl { get; set; }
        public virtual DbSet<Product_tbl> Product_tbl { get; set; }
        public virtual DbSet<Schedule_Tbl> Schedule_Tbl { get; set; }
        public virtual DbSet<Students_Tbl> Students_Tbl { get; set; }
        public virtual DbSet<Teams_Tbl> Teams_Tbl { get; set; }
        public virtual DbSet<WorkShop_Tbl> WorkShop_Tbl { get; set; }
    }
}
