//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Swim4Life
{
    using System;
    using System.Collections.Generic;
    
    public partial class Schedule_Tbl
    {
        public int ScheduleId { get; set; }
        public int SchedulePoolId { get; set; }
        public int ScheduleTeamId { get; set; }
        public string ScheduleDate { get; set; }
        public string Team { get; set; }
        public string Pool { get; set; }
    
        public virtual Pool_Tbl Pool_Tbl { get; set; }
        public virtual Teams_Tbl Teams_Tbl { get; set; }
    }
}
